/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/toplevel": {
    get: {
      responses: {
        /** Array of collections */
        200: {
          content: {
            "application/json": components["schemas"]["TopLevel"];
          };
        };
      };
    };
  };
  "/document": {
    get: {
      responses: {
        /** Firestore Document */
        200: {
          content: {
            "application/json": components["schemas"]["Document"];
          };
        };
      };
    };
  };
  "/collection": {
    get: {
      responses: {
        /** Firestore Document */
        200: {
          content: {
            "application/json": components["schemas"]["Collection"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    /** @description A object to count the successfully written docs and the the failed docs / collections. */
    Summary: {
      /** @example 23 */
      docs: number;
      /** @example 2 */
      docErrors: number;
      collectionErrors: number;
    };
    /** @description The top level of the json on item collection with an array of Collection */
    TopLevel: {
      collection: components["schemas"]["Collection"][];
    };
    Collection: {
      /**
       * @description the name of the collection. must be a valid collection name and not empty.
       * @example collectionName
       */
      name: string;
      /** @description An array of documents, to be added to this collection */
      docs: components["schemas"]["Document"][];
    };
    Document: {
      /**
       * @description the name of document, when it is an empty string (e.g. "") Firestore will choose an random doc name
       * @example documentName
       */
      name: string;
      /** @description the actuall data of the document. note, that field functions like server time or so are not supported yet, as well as the date field itself. */
      data: { [key: string]: unknown };
      /** @description an array of sub collections for this document */
      collection: components["schemas"]["Collection"][] | null;
    };
  };
}

export interface operations {}

export interface external {}
